os: windows
language: cpp

before_install:
  - where choco
  - where mingw32-make
  - $env:path="C:\\ProgramData\\chocolatey\\bin;"+$env:path
  - C:\\ProgramData\\chocolatey\\bin\\choco.exe -?
  - choco -?

script:
 - g++ -o test main.cpp

after_success:
 - ls .
