os: windows
language: cpp

before_install:
  - where choco
  - where mingw32-make
  - set Path=C:\\ProgramData\\chocolatey\\bin;%Path%
  - C:\\ProgramData\\chocolatey\\bin\\choco.exe -?
  - choco -?

script:
 - g++ -o test main.cpp

after_success:
 - ls .
