os: windows
language: cpp

before_install:
  - where choco
  - where mingw32-make
#  - dir C:\
  - C:\ProgramData\chocolatey\bin\choco.exe /V
  - choco /v

script:
 - g++ -o test main.cpp

after_success:
 - ls .